config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/index'
  get 'pages/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users do
    member do
      get 'product'
    end
    collection do
      get 'search'
    end
  end
  resources :products do
    collection do
      get 'search'
    end
    resources :likes, only: %i[index create destroy]
  end

  resources :messages, only: [:create]

  resources :rooms, only: %i[create show index]

  resources :diaries

  scope '(:locale)' do
    resources :users, except: :create do
      member do
        get :followings, :followers
      end
    end
    resource :user_icons, only: :destroy
    resources :relationships, only: %I[create destroy]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
# frozen_string_literal: true

class Diary < ApplicationRecord
  belongs_to :user
  has_many :diary_details, dependent: :destroy
  accepts_nested_attributes_for :diary_details, allow_destroy: true

  validates :title, presence: true
end

app/models/diary_detail.rb
# frozen_string_literal: true

class DiaryDetail < ApplicationRecord
  belongs_to :diary

  validates :diary_product_name, presence: true
  validates :diary_product_price, presence: true
  validates :diary_product_alcohol, presence: true
end

app/models/entry.rb
# frozen_string_literal: true

class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates_uniqueness_of :product_id, scope: :user_id
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  validates :product_name, presence: true
  validates :product_price, presence: true
  validates :product_alcohol, presence: true

  mount_uploader :product_image, ImageUploader

  def self.search(search)
    if search
      Product.where([
                      'product_name LIKE(?) OR product_price LIKE(?) OR product_introduction LIKE(?) OR product_alcohol LIKE(?) OR product_company LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"
                    ])
    else
      Product.all
    end
  end
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :password, presence: true, length: { minimum: 6 },
                       format: { with: /\A[a-z0-9]+\z/i, message: '英数字以外の文字を含めることは出来ません' }
  validates :email, presence: true, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: '英数字以外の文字を含めることは出来ません' }

  mount_uploader :image, ImageUploader

  has_many :followers,
           class_name: 'Relationship',
           foreign_key: 'follower_id',
           dependent: :destroy,
           inverse_of: :follower
  has_many :followings,
           class_name: 'Relationship',
           foreign_key: 'following_id',
           dependent: :destroy,
           inverse_of: :following

  has_many :following_users, through: :followers, source: :following
  has_many :follower_users, through: :followings, source: :follower

  has_many :products
  has_many :likes, dependent: :destroy
  has_many :liked_products, through: :likes, source: :product

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :diaries

  def already_liked?(product)
    likes.exists?(product_id: product.id)
  end

  def follow(other_user_id)
    followers.create(following_id: other_user_id)
  end

  def following?(other_user)
    following_users.include?(other_user)
  end

  def self.search(search)
    if search
      User.where(['username LIKE(?) OR profile LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      User.all
    end
  end
end

app/controllers/diaries_controller.rb
# frozen_string_literal: true

class DiariesController < ApplicationController
  def index
    @diaries = Diary.all
  end

  def new
    @diary = Diary.new
    @diary.diary_details.build
  end

  def show
    @diary = Diary.find(params[:id])
    @diary_details = @diary.diary_details
    @total_price = @diary_details.sum(:diary_product_price)
  end

  def create
    @diary = Diary.new(diary_params)
    @diary.user_id = current_user.id
    if @diary.save
      redirect_to diary_path(@diary)
    else
      render 'new'
    end
  end

  def destroy
    @diary = Diary.find(params[:id])
    @diary.destroy
    redirect_to diaries_path, notice: '削除しました'
  end

  def edit
    @diary = Diary.find(params[:id])
  end

  def update
    @diary = Diary.find(params[:id])
    if @diary.update(diary_params)
      redirect_to diary_path(@diary), notice: '編集しました'
    else
      render 'edit'
    end
  end

  private

  def diary_params
    params.require(:diary).permit(
      :title,
      :content,
      :start_time,
      :product_name,
      :product_alcohol,
      :product_price,
      :impression,
      :id,
      diary_details_attributes: %i[
        id
        diary_product_name
        diary_product_alcohol
        diary_product_price
        impression
        total
        _destroy
      ]
    ).merge(user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def index
    user_id = current_user.id
    @user = User.find(user_id)
    @like = Like.find_by(product_id: params[:product_id], user_id: current_user.id)
  end

  def create
    @like = current_user.likes.create(product_id: params[:product_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(product_id: params[:product_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end

  def show; end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
      @user_name = @room.messages && @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/chats_helper.rb
# frozen_string_literal: true

module ChatsHelper
end

app/helpers/diaries_helper.rb
# frozen_string_literal: true

module DiariesHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/diaries/_diary_detail_fields.html.erb
<div class="nested-fields">
  <div class="diary_product">
    <div class="diary_product_input">
      <%= f.text_field :diary_product_name, placeholder: "商品名" %>
    </div>
    <div class="diary_product_input">
      <%= f.number_field :diary_product_price, placeholder: "価格", min:"0" %>円
    </div>
    <div class="diary_product_input">
      <%= f.number_field :diary_product_alcohol, placeholder: "アルコール度数", min:"0" %>%
    </div>
    <div class="delete_button">
      <%= f.link_to_remove '削除' %>
    </div>
  </div>
</div> 

app/views/diaries/edit.html.erb
<div class="diary_outer_border">
  <div class="diary_inner_border">
    <div class="proposition">
      <h2>日記編集</h2>
    </div>
    <div class="edit_space">
      <%= link_to '日記削除',diary_path(@diary.id), method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <div class="diary_contents">
      <%= nested_form_for @diary do |f| %>
        <% if @diary.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@diary.errors.count, "エラー") %></h2>
            <ul>
              <% @diary.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="diary_contents_form">
          <div class="diary_head">
            <div class="diary_title">
              <%= f.label :title, "タイトル" %>
              <%= f.text_field :title %>
            </div>
            <div class="diary_time">
              <%= f.label :start_time, "日時" %>
              <%= f.datetime_select :start_time %>
            </div>
          </div>
          <%= f.fields_for :diary_details do |d| %>
            <%= render "diary_detail_fields", f: d %>
          <% end %>
          <div class="addition_button">
            <%= f.link_to_add '+ 追加', :diary_details %>
          </div>
          <div class="impression">
            <div class="impression_label">
              <%= f.label :impression, "感想" %>
            </div>
            <div class="impression_input">
              <%= f.text_area :impression %>
            </div>
          </div>
        </div>
        <div class="diary_submit_button">
          <%= f.submit "編集完了"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/diaries/index.html.erb
<div class="diary_outer_border">
  <div class="diary_inner_border">
    <div class="proposition">
      <h2>日記</h2>
    </div>  
    <div class="diary_registration">
      <%= link_to  new_diary_path do%>
        <p class="diary_p">日記を書く</p>
      <% end %>
    </div>  
    <%= month_calendar events: @diaries do |date, diaries| %>
    <%= date.day %>
    <% diaries.each do |diary| %>
      <% if current_user.id == diary.user_id  %>
        <%= link_to diary.title, diary %>
      <% else %>
        
      <% end %>
    <% end %>
  <% end %>
  </div>
</div>
<%= @total_price %>

app/views/diaries/new.html.erb
<div class="diary_outer_border">
  <div class="diary_inner_border">
    <div class="proposition">
      <h2>日記</h2>
    </div>
    <div class="diary_contents">
      <%= nested_form_for @diary do |f| %>
        <% if @diary.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@diary.errors.count, "エラー") %></h2>
            <ul>
              <% @diary.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="diary_contents_form">
          <div class="diary_head">
            <div class="diary_title">
              <%= f.label :title, "タイトル" %>
              <%= f.text_field :title %>
            </div>
            <div class="diary_time">
              <%= f.label :start_time, "日時" %>
              <%= f.datetime_select :start_time %>
            </div>
          </div>
          <%= f.fields_for :diary_details do |d| %>
            <%= render "diary_detail_fields", f: d %>
          <% end %>
          <div class="addition_button">
            <%= f.link_to_add '+ 追加', :diary_details %>
          </div>
          <div class="impression">
            <div class="impression_label">
              <%= f.label :impression, "感想" %>
            </div>
            <div class="impression_input">
              <%= f.text_area :impression %>
            </div>
          </div>
        </div>
        <div class="diary_submit_button">
          <%= f.submit "登録"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/diaries/show.html.erb
<div class="diary_outer_border">
  <div class="diary_inner_border">
    <div class="proposition">
      <h2>日記詳細</h2>
    </div>
    <div class="edit_space">
      <%= link_to '編集', edit_diary_path(@diary) %>
    </div>
    <div class="diary_contents">
      <div class="diary_head">
        <div class="diary_title_show">
          <%= @diary.title %>
        </div>
        <div class="diary_time_show">
          <%= @diary.start_time.strftime("%Y-%m-%d %H:%M") %>
        </div>
      </div>
      <div class="diary_border_botoom">
        <table class="diary_show_table">
          <tr>
            <th>商品名</th>
            <th>アルコール度数</th>
            <th>金額</th>
          </tr>
          <% @diary_details.each do |c| %>
            <tr>
              <td><%= c.diary_product_name%></td>
              <td class="right_justified"><%= c.diary_product_alcohol%>%</td>
              <td class="right_justified"><%= c.diary_product_price%>円</td>
            </tr>
          <% end %>
        </table>
        <div class="diary_total_price_area">
          <div class="diary_total_price_label">
            <p>合計金額</p>
          </div>
          <div class="diary_total_price">
            <%= @total_price %>円
          </div>
        </div>
      </div>
      <div class="diary_impression_show">
        <%= @diary.impression %>
      </div>
    </div>
  </div>
</div>
<div class="back">
  <%= link_to '戻る', diaries_path %> 
</div>