config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/index'
  get 'pages/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users do
    member do
      get 'product'
    end
    collection do
      get 'search'
    end
  end
  resources :products do
    collection do
      get 'search'
    end
    resources :likes, only: %i[index create destroy]
  end

  resources :messages, only: [:create]

  resources :rooms, only: %i[create show index]

  resources :diaries

  scope '(:locale)' do
    resources :users, except: :create do
      member do
        get :followings, :followers
      end
    end
    resource :user_icons, only: :destroy
    resources :relationships, only: %I[create destroy]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :password, presence: true, length: { minimum: 6 },
                       format: { with: /\A[a-z0-9]+\z/i, message: '英数字以外の文字を含めることは出来ません' }
  validates :email, presence: true, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: '英数字以外の文字を含めることは出来ません' }

  mount_uploader :image, ImageUploader

  has_many :followers,
           class_name: 'Relationship',
           foreign_key: 'follower_id',
           dependent: :destroy,
           inverse_of: :follower
  has_many :followings,
           class_name: 'Relationship',
           foreign_key: 'following_id',
           dependent: :destroy,
           inverse_of: :following

  has_many :following_users, through: :followers, source: :following
  has_many :follower_users, through: :followings, source: :follower

  has_many :products
  has_many :likes, dependent: :destroy
  has_many :liked_products, through: :likes, source: :product

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :diaries

  def already_liked?(product)
    likes.exists?(product_id: product.id)
  end

  def follow(other_user_id)
    followers.create(following_id: other_user_id)
  end

  def following?(other_user)
    following_users.include?(other_user)
  end

  def self.search(search)
    if search
      User.where(['username LIKE(?) OR profile LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      User.all
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    protected

    def after_update_path_for(_resource)
      user_path(current_user)
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %I[show edit update destroy product followings followers]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    return if @user.id == current_user.id

    @current_user_entry.each do |cu|
      @user_entry.each do |u|
        if cu.room_id == u.room_id
          @is_room = true
          @room_id = cu.room_id
        end
      end
    end
    return if @is_room

    @room = Room.new
    @entry = Entry.new
  end

  def followings
    @followings = @user.following_users
  end

  def followers
    @followers = @user.follower_users
  end

  def product
    @user = User.find(params[:id])
    @products = Product.where(user_id: @user.id)
  end

  def search
    @user = User.search(params[:search])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/followers.html.erb
<div class="outer_border">
  <div class="inner_border_follow">
    <div class="follow_list_title">
      <h2>フォロワー</h2>
    </div>
    <div class="follow_list">
      <% if @followers.present?%>
        <% @followers.each do |user| %>
          <%= link_to user_path(user) do %>
            <div class="follow_content">
              <div class="follow_image">
                <% if user.image? %>
                  <img src="<%= user.image %>" class="icon_image user_show_icon" alt="ユーザーアイコン">
                <% else %>
                  <img src="/assets/default.png" class="icon_image user_show_icon" alt="ユーザーアイコン" %>
                <% end %>
              </div>
              <div class="follow_content_right">
                <div class="follow_name_index">
                  <%= user.username %>
                </div>
                <div class="follow_profile_index">
                  <%= user.profile %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <div class="not_follow">
          <p>フォロワーがいません</p>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= link_to ("ユーザー詳細へ戻る"), user_path %>

app/views/users/followings.html.erb
<div class="outer_border">
  <div class="inner_border_follow">
    <div class="follow_list_title">
      <h2>フォロー中</h2>
    </div>
    <div class="follow_list">
      <% if @followings.present?%>
        <% @followings.each do |user| %>
          <%= link_to user_path(user) do %>
            <div class="follow_content">
              <div class="follow_image">
                <% if user.image? %>
                  <img src="<%= user.image %>" class="icon_image user_show_icon" alt="ユーザーアイコン">
                <% else %>
                  <img src="/assets/default.png" class="icon_image user_show_icon" alt="ユーザーアイコン" %>
                <% end %>
              </div>
              <div class="follow_content_right">
                <div class="follow_name_index">
                  <%= user.username %>
                </div>
                <div class="follow_profile_index">
                  <%= user.profile %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <div class="not_follow">
          <p>フォローしていません</p>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to ("ユーザー詳細へ戻る"), user_path %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<h1>All users</h1>
<h2>ログイン中のユーザー名</h2>
<ul class="users">
<% @users.each do |user| %>
  <li>
    <%= link_to user do %>
      <%= user.username%>
    <% end %>
  </li>
<% end %>
</ul>

app/views/users/product.html.erb
<div class="outer_border">
  <div class="inner_border_product">
    <div class="product_list_title">
      <h2>投稿一覧</h2>
    </div>
    <div class="product_list">
      <% if @products.present?%>
        <% @products.each do |product| %>
          <%= link_to product_path(product.id) do %>
            <div class="product_content">
              <div class="product_image_area">
                <% if product.product_image? %>
                  <img src="<%= product.product_image %>" class="icon_image user_show_icon" alt="商品画像">
                <% else %>
                  <img src="/assets/not_image.png" class="icon_image user_show_icon" alt="not_image" %>
                <% end %>
              </div>
              <div class="product_content_right">
                <div class="product_appeal_index">
                  <%= product.appeal %>
                </div>
                <div class="product_name_index">
                  <%= product.product_name%>
                </div>
                <div class="product_evaluation_index">
                  <div id="star-rate-<%= product.id %>"></div>
                    <script>
                    $('#star-rate-<%= product.id %>').empty();
                      $('#star-rate-<%= product.id %>').raty({
                        size: 36,
                        starOff:  '<%= asset_path('star-off.png') %>',
                        starOn : '<%= asset_path('star-on.png') %>',
                        starHalf: '<%= asset_path('star-half.png') %>',
                        half: true,
                        readOnly: true,
                        score: <%= product.evaluation %>,
                      });
                    </script>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <div class="not_product">
          <p>投稿がありません</p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<div class="outer_border">
  <div class="inner_border_product">
    <div class="serach_title">
      <h2>検索</h2>
    </div>
    <div class="search_top_text">
      <p>
        あなたと気の合う飲み友を探せます
      </p>
    </div>
    <div class="search_input">
      <%= form_tag(search_users_path,:method => 'get') do %>
        <div class="search_input_area">
          <%= text_field_tag :search %>
        </div>
        <div class="search_btn">
          <%= submit_tag 'Search', :name => nil %>
        </div>
      <% end %>
    </div>
    <div class="user_list">
      <% @user.each do |user| %>
        <% unless user.id == current_user.id %>
          <%= link_to user_path(user.id) do %>
            <div class="user_search_content">
              <div class="product_image_search">
                <% if user.image? %>
                  <img src="<%= user.image %>" class="icon_image user_show_icon" alt="ユーザーアイコン">
                <% else %>
                  <img src="/assets/default.png" class="icon_image user_show_icon" alt="ユーザーアイコン" %>
                <% end %>
              </div>
              <div class="user_content_right search_user_content_right">
                <div class="username_index search_username_index">
                  <%= user.username %>
                </div>
                <div class="user_profile_index
                search_user_profile_index">
                  <%= user.profile %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="outer_border">
  <div class="content_user_show">
    <div class="user_infomation">
      <h2 class="user_name"><%= @user.username %></h2>
      <% if @user.image? %>
        <img src="<%= @user.image %>" class="icon_image user_show_icon" alt="ユーザーアイコン">
      <% else %>
        <img src="/assets/default.png" class="icon_image user_show_icon" alt="ユーザーアイコン" %>
      <% end %>
    </div>
    <div class="function">
      <div class="function_top">
        <div class="function_list">
          <%= link_to "#{@user.followers.count} #{User.human_attribute_name("フォロー")}", followings_user_path(@user) %> 
        </div>
        <div class="function_list">
          <%= link_to "#{@user.followings.count} #{User.human_attribute_name("フォロワー")}", followers_user_path(@user) %>
        </div>
        <div class="function_list">
          <%= link_to "投稿一覧", product_user_path(@user.id) %>
        </div>
      </div>
      <div class="function_bottom">
        <div class="user_profile">
          <%= @user.profile %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="functions">
    <% if @user.id == current_user.id %>
      <div class="function_details">
        <%= link_to edit_user_registration_path do %>
          <div class="function_detail function_detail_edit function_border_left">
            <img src="/assets/icon_edit.png", class="function_detail_icon icon_a">
            <p>アカウント編集</p>
          </div>
        <% end %>
      </div>
      <div class="function_details">
        <%= link_to new_product_path do %>
          <div class="function_detail function_detail_product_new">
            <img src="/assets/icon_registration.png", class="function_detail_icon">
            <p>商品登録</p>
          </div>
        <% end %>
      </div>
      <div class="function_details">
        <%= link_to product_likes_path(@user) do %>
          <div class="function_detail function_detail_like">
            <img src="/assets/icon_like.png", class="function_detail_icon">
            <p>いいねした投稿</p>
          </div>
        <% end %>
      </div>
      <div class="function_details">
        <%= link_to diaries_path do%>
          <div class="function_detail function_border_right function_detai_diary" >
            <img src="/assets/icon_diary.png", class="function_detail_icon">
            <p>日記をかく</p>
          </div>
        <% end %>
      </div>
    <% else %>
      
    <% end %>
  </div>
  <% unless @user == current_user %>
    <div class="chat_button">
      <% if @is_room == true %>
        <a href="/rooms/<%= @room_id %>">チャット</a>
      <% else %>
        <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, :value=> @user.id %>
          <% end %>
          <%= f.submit "チャット" %>
        <% end %>
      <% end %>
    </div>
    <% if current_user.following?(@user) %>
      <div class="follow_btn no_follow_btn">
        <%= button_to ('フォローを解除する'), relationship_path, method: :delete %>
      </div>
    <% else %>
      <%= form_for(@user.followers.build) do |f| %>
        <div class="follow_btn yes_follow_btn">
          <%= hidden_field_tag :follow_id, @user.id %>
          <%= f.submit ('フォローする') %>
        </div>  
      <% end %>
    <% end %>
  <% end %>
</div>