config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/index'
  get 'pages/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users do
    member do
      get 'product'
    end
    collection do
      get 'search'
    end
  end
  resources :products do
    collection do
      get 'search'
    end
    resources :likes, only: %i[index create destroy]
  end

  resources :messages, only: [:create]

  resources :rooms, only: %i[create show index]

  resources :diaries

  scope '(:locale)' do
    resources :users, except: :create do
      member do
        get :followings, :followers
      end
    end
    resource :user_icons, only: :destroy
    resources :relationships, only: %I[create destroy]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
# frozen_string_literal: true

class Diary < ApplicationRecord
  belongs_to :user
  has_many :diary_details, dependent: :destroy
  accepts_nested_attributes_for :diary_details, allow_destroy: true

  validates :title, presence: true
end

app/models/diary_detail.rb
# frozen_string_literal: true

class DiaryDetail < ApplicationRecord
  belongs_to :diary

  validates :diary_product_name, presence: true
  validates :diary_product_price, presence: true
  validates :diary_product_alcohol, presence: true
end

app/models/entry.rb
# frozen_string_literal: true

class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates_uniqueness_of :product_id, scope: :user_id
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  validates :product_name, presence: true
  validates :product_price, presence: true
  validates :product_alcohol, presence: true

  mount_uploader :product_image, ImageUploader

  def self.search(search)
    if search
      Product.where([
                      'product_name LIKE(?) OR product_price LIKE(?) OR product_introduction LIKE(?) OR product_alcohol LIKE(?) OR product_company LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"
                    ])
    else
      Product.all
    end
  end
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :password, presence: true, length: { minimum: 6 },
                       format: { with: /\A[a-z0-9]+\z/i, message: '英数字以外の文字を含めることは出来ません' }
  validates :email, presence: true, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: '英数字以外の文字を含めることは出来ません' }

  mount_uploader :image, ImageUploader

  has_many :followers,
           class_name: 'Relationship',
           foreign_key: 'follower_id',
           dependent: :destroy,
           inverse_of: :follower
  has_many :followings,
           class_name: 'Relationship',
           foreign_key: 'following_id',
           dependent: :destroy,
           inverse_of: :following

  has_many :following_users, through: :followers, source: :following
  has_many :follower_users, through: :followings, source: :follower

  has_many :products
  has_many :likes, dependent: :destroy
  has_many :liked_products, through: :likes, source: :product

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :diaries

  def already_liked?(product)
    likes.exists?(product_id: product.id)
  end

  def follow(other_user_id)
    followers.create(following_id: other_user_id)
  end

  def following?(other_user)
    following_users.include?(other_user)
  end

  def self.search(search)
    if search
      User.where(['username LIKE(?) OR profile LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      User.all
    end
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def index
    user_id = current_user.id
    @user = User.find(user_id)
    @like = Like.find_by(product_id: params[:product_id], user_id: current_user.id)
  end

  def create
    @like = current_user.likes.create(product_id: params[:product_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(product_id: params[:product_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/chats_helper.rb
# frozen_string_literal: true

module ChatsHelper
end

app/helpers/diaries_helper.rb
# frozen_string_literal: true

module DiariesHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>portfoio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= render 'shared/header' %>
      <div class='container'>
        <%= yield %>
      </div>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="p_top">
  <div class="heading_area">
    <div class="heading">
      <h2>酒楽 ~ Liqour Enjoy ~</h2>
    </div>
    <div class="sub_title">
      <p>
        新しいお酒の楽しみ方を探してみませんか?
      </p>
    </div>
  </div>
  <div class="top_image">
    <div class="top_image_area">
      <img class="top_image_photo" src="/assets/top_beer.jpg">
    </div>
  </div>
</div>
<div class="wave">
  <canvas id="waveCanvas"></canvas>
</div>
<div class="service_list bg">
  <div class="service_area">
    <div class="service">
      <% if user_signed_in? %>
        <%= link_to search_products_path do %>
          <img src="/assets/icon_search.png", class="top_service_icon">
          <h2 class="service_text">好きなお酒を見つける</h2>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <img src="/assets/icon_search.png", class="top_service_icon">
          <h2 class="service_text">好きなお酒を見つける</h2>
        <% end %>
      <% end %>
    </div>
    <div class="service_sentence">
      <p>
        あなたの美味いがここにある<br>
        様々なワードから検索できます
      </p>
    </div>
  </div>
  <div class="service_area service_area_wide">
    <div class="service">
       <% if user_signed_in? %>
        <%= link_to new_product_path do %>
          <img src="/assets/icon_post.png", class="top_service_icon">
          <h2 class="service_text">飲んだお酒を共有する</h2>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <img src="/assets/icon_post.png", class="top_service_icon">
          <h2 class="service_text">飲んだお酒を共有する</h2>
        <% end %>
      <% end %>
    </div>
    <div class="service_sentence">
      <p>
        飲んだお酒を投稿し共有しましょう
      </p>
    </div>
  </div>
  <div class="service_area">
    <div class="service">
       <% if user_signed_in? %>
        <%= link_to search_users_path do %>
          <img src="/assets/icon_friend.png", class="top_service_icon">
          <h2 class="service_text_friend">飲み友を見つける</h2>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <img src="/assets/icon_friend.png", class="top_service_icon">
          <h2 class="service_text_friend">飲み友を見つける</h2>
        <% end %>
      <% end %>
    </div>
    <div class="service_sentence">
      <p>
        お酒を飲み合える「飲み友」を探しましょう
      </p>
    </div>
  </div>
  <div class="service_area service_area_wide">
    <div class="service">
       <% if user_signed_in? %>
        <%= link_to diaries_path do %>
          <img src="/assets/icon_diary.png", class="top_service_icon">
          <h2 class="service_text">飲んだお酒を管理する</h2>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <img src="/assets/icon_diary.png", class="top_service_icon">
          <h2 class="service_text">飲んだお酒を管理する</h2>
        <% end %>
      <% end %>
    </div>
    <div class="service_sentence service_sentence_under">
      <p>
        飲んだお酒を記録し思い出に残しましょう<br>
        金額等も入力し管理できます
      </p>
    </div>
  </div>
</div>
<script src="/assets/bubble.js"></script>
<script src="/assets/wave.js"></script>

app/views/shared/_footer.html.erb
<footer>
  <h1 class="footer_title">
    <%= link_to pages_index_path, data: {"turbolinks" => false} do%>
        酒 楽
    <% end %>
  </h1>
</footer>

app/views/shared/_header.html.erb
<header>
  <%= link_to pages_index_path, data: {"turbolinks" => false} do%>
    <h1 class="header_title">
        酒楽
    </h1>
  <% end %>
  <nav>
    <% if user_signed_in? %>
      <div class="header_contents">
        <ul>
          <li class="header_content"><%= link_to'検索', search_products_path %></li>
          <li class="header_content"><%= link_to'投稿', new_product_path %></li>
          <li class="header_content">
            <label for="toggle" onclick=""  for="menuToggle" class="login_user">
              <p class="header_user_name"><%= current_user.username %></p>
            </label>  
            <input type="checkbox" id="toggle" autocomplete="off">
            <ul id="menu" class="user_pulldown">  
              <li class="pulldown"><%= link_to 'プロフィール', user_path(current_user.id) %></li>
              <li class="pulldown"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      </div>
    <% else %>
      <div class="header_not_login">
        <%= link_to 'サインアップ', new_user_registration_path %>
        <%= link_to 'ログイン', new_user_session_path %>
      </div>
    <% end %>
  </nav>
</header>

app/views/shared/_test_login.html.erb
<div class="btn">
  <%= form_for(User.new, url:new_user_session_url) do |f| %>
    <%= f.hidden_field :email, value: "xx@example.com" %>
    <%= f.hidden_field :password, value: "password" %>
    <%= f.submit "テストアカウントでログイン"%>
  <% end %>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= start_date.year %>/
    <%= t('date.month_names')[start_date.month] %> </span>
    <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>