config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/index'
  get 'pages/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users do
    member do
      get 'product'
    end
    collection do
      get 'search'
    end
  end
  resources :products do
    collection do
      get 'search'
    end
    resources :likes, only: %i[index create destroy]
  end

  resources :messages, only: [:create]

  resources :rooms, only: %i[create show index]

  resources :diaries

  scope '(:locale)' do
    resources :users, except: :create do
      member do
        get :followings, :followers
      end
    end
    resource :user_icons, only: :destroy
    resources :relationships, only: %I[create destroy]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
# frozen_string_literal: true

class Diary < ApplicationRecord
  belongs_to :user
  has_many :diary_details, dependent: :destroy
  accepts_nested_attributes_for :diary_details, allow_destroy: true

  validates :title, presence: true
end

app/models/diary_detail.rb
# frozen_string_literal: true

class DiaryDetail < ApplicationRecord
  belongs_to :diary

  validates :diary_product_name, presence: true
  validates :diary_product_price, presence: true
  validates :diary_product_alcohol, presence: true
end

app/models/entry.rb
# frozen_string_literal: true

class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates_uniqueness_of :product_id, scope: :user_id
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  validates :product_name, presence: true
  validates :product_price, presence: true
  validates :product_alcohol, presence: true

  mount_uploader :product_image, ImageUploader

  def self.search(search)
    if search
      Product.where([
                      'product_name LIKE(?) OR product_price LIKE(?) OR product_introduction LIKE(?) OR product_alcohol LIKE(?) OR product_company LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"
                    ])
    else
      Product.all
    end
  end
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :password, presence: true, length: { minimum: 6 },
                       format: { with: /\A[a-z0-9]+\z/i, message: '英数字以外の文字を含めることは出来ません' }
  validates :email, presence: true, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: '英数字以外の文字を含めることは出来ません' }

  mount_uploader :image, ImageUploader

  has_many :followers,
           class_name: 'Relationship',
           foreign_key: 'follower_id',
           dependent: :destroy,
           inverse_of: :follower
  has_many :followings,
           class_name: 'Relationship',
           foreign_key: 'following_id',
           dependent: :destroy,
           inverse_of: :following

  has_many :following_users, through: :followers, source: :following
  has_many :follower_users, through: :followings, source: :follower

  has_many :products
  has_many :likes, dependent: :destroy
  has_many :liked_products, through: :likes, source: :product

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :diaries

  def already_liked?(product)
    likes.exists?(product_id: product.id)
  end

  def follow(other_user_id)
    followers.create(following_id: other_user_id)
  end

  def following?(other_user)
    following_users.include?(other_user)
  end

  def self.search(search)
    if search
      User.where(['username LIKE(?) OR profile LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      User.all
    end
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def index
    user_id = current_user.id
    @user = User.find(user_id)
    @like = Like.find_by(product_id: params[:product_id], user_id: current_user.id)
  end

  def create
    @like = current_user.likes.create(product_id: params[:product_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(product_id: params[:product_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end

  def show; end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products  = Product.all
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
    @user = User.find_by(id: @product.user_id)
    @like = Like.new
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      flash[:success] = '商品を投稿しました'
      redirect_to product_user_path(@product.user_id)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:success] = 'product deleted'
    redirect_to product_user_path(@product.user_id)
  end

  def search
    @product = Product.search(params[:search])
  end

  private

  def product_params
    params.require(:product).permit(:product_name, :product_price, :product_introduction, :product_alcohol,
                                    :product_company, :id, :product_image, :appeal, :evaluation)
  end

  def ensure_current_user
    product = Product.find(params[:id])
    redirect_to action: :index if product.user_id != current_user.id
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
      @user_name = @room.messages && @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/chats_helper.rb
# frozen_string_literal: true

module ChatsHelper
end

app/helpers/diaries_helper.rb
# frozen_string_literal: true

module DiariesHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/products/edit.html.erb
<div class="outer_border">
  <div class="inner_border">
    <div class="title_block">
      <h1 class="title">商品情報編集</h1>
    </div>
    <%= form_for @product do |f| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "エラー") %></h2>
          <ul>
            <% @product.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <div class="input_container">
      <div class="field">
        <div class="input_label">
          <%= f.label :イメージ画像 %><br/>
        </div>
        <div class="input_area">
          <%= f.file_field :product_image %>
        </div>
      </div>
      <div class="field">
        <div class="input_label">
          <%= f.label :商品名 %><br />
        </div>
        <div class="input_area">
          <%= f.text_field :product_name, autofocus: true %>
        </div>
      </div>
      <div class="field">
        <div class="input_label">
          <%= f.label :アピール文 %><br />
        </div>
        <div class="input_area">
          <%= f.text_field :appeal, autofocus: true %>
        </div>
      </div>
      <div class="field">
        <div class="input_label">
          <%= f.label :価格 %><br />
        </div>
        <div class="input_area">
          <%= f.text_field :product_price, autofocus: true %>円
        </div>
      </div>
      <div class="field">
        <div class="input_label">
          <%= f.label :商品紹介 %><br />
        </div>
        <div class="input_area">
          <%= f.text_area :product_introduction, autofocus: true %>
        </div>
      </div>
      <div class="field">
        <div class="input_label">
          <%= f.label :アルコール度数 %><br />
        </div>
        <div class="input_area">
          <%= f.text_field :product_alcohol, autofocus: true %>%
        </div>
      </div>
      <div class="field">
        <div class="input_label">
          <%= f.label :販売会社 %><br />
        </div>
        <div class="input_area">
          <%= f.text_field :product_company, autofocus: true %>
        </div>
      </div>
      <div class="field">
        <div class="input_label" id="star">
          <%= f.label :evaluation,'評価' %><br>
          <%= f.hidden_field :evaluation, id: :review_star %>
          <script>
            $('#star').raty({
              size     : 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              scoreName: 'product[evaluation]',
              half: true,
            });
          </script>
        </div>
      </div>
    </div>
    <div class="creation_btn btn">
      <%= f.submit '更新' %>
    </div>
    <% end %>
  </div>
  <div class="back">
    <%= link_to "戻る", :back %>
  </div>
</div>

app/views/products/index.html.erb
<h2>index</h2>
<table border="1">
  <tr>
    <th><p>商品名</p></th>
    <th><p>価格</p></th>
    <th><p>紹介文</p></th>
    <th><p>アルコール度数</p></th>
    <th><p>販売会社</p></th>
  </tr>
  <% @products.each do |product| %>
  <tr>
    <td><%= product.product_name%></td>
    <td><%= product.product_price%></td>
    <td><%= product.product_introduction%></td>
    <td><%= product.product_alcohol%></td>
    <td><%= product.product_company%></td>
  </tr>
  <% end %>
</table>
<% @products.each do |product| %>
  <li>
    <%= link_to product do %>
      <%= product.product_name %>
    <% end %>
  </li>
<% end %>

<%= link_to '検索', search_products_path %>

app/views/products/new.html.erb
<div class="outer_border">
  <div class="inner_border">
    <div class="title_block">
      <h1 class="title">投稿</h1>
    </div>
    <%= form_for @product do |f| %>
    <div class="input_container">
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "エラー") %></h2>
          <ul>
            <% @product.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
         <div class="input_label">
          <%= f.label :イメージ画像 %><br/>
        </div>
        <div class="input_area">
          <%= f.file_field :product_image %>
        </div>
      </div>
      <div class="field">
         <div class="input_label">
          <%= f.label :商品名 %><br />
        </div>
        <div class="input_area">
          <%= f.text_field :product_name, autofocus: true %>
        </div>
      </div>
      <div class="field">
         <div class="input_label">
          <%= f.label :アピール文 %><br />
        </div>
        <div class="input_area">
          <%= f.text_field :appeal, autofocus: true %>
        </div>
      </div>
      <div class="field">
         <div class="input_label">
          <%= f.label :価格 %><br />
        </div>
        <div class="input_area">
          <%= f.text_field :product_price, autofocus: true %>円
        </div>
      </div>
      <div class="field">
         <div class="input_label">
          <%= f.label :商品紹介 %><br />
        </div>
        <div class="input_area">
          <%= f.text_area :product_introduction, autofocus: true %>
        </div>
      </div>
      <div class="field">
         <div class="input_label">
          <%= f.label :アルコール度数 %><br />
        </div>
        <div class="input_area">
          <%= f.text_field :product_alcohol, autofocus: true %>%
        </div>
      </div>
      <div class="field">
       <div class="input_label">
          <%= f.label :販売会社 %><br />
        </div>
        <div class="input_area">
          <%= f.text_field :product_company, autofocus: true %>
        </div>
      </div>
      <div class="field">
        <div class="input_label" id="star">
          <%= f.label :evaluation,'評価' %><br>
          <%= f.hidden_field :evaluation, id: :review_star %>
          <script>
            $('#star').raty({
              size     : 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              scoreName: 'product[evaluation]',
              half: true,
            });
          </script>
        </div>
      </div>
    </div>
    <div class="login_btn btn">
      <%= f.submit '登録' %>
    </div>
    <% end %>
  </div>
</div>

app/views/products/search.html.erb
<div class="outer_border">
  <div class="inner_border_product">
    <div class="serach_title">
      <h2>検索</h2>
    </div>
    <div class="search_top_text">
      <p>
        色々なワードで検索して<br>
        あなた好みのお酒を探せます
      </p>
    </div>
    <div class="search_input">
      <%= form_tag(search_products_path,:method => 'get') do %>
        <div class="search_input_area">
          <%= text_field_tag :search %>
        </div>
        <div class="search_btn">
          <%= submit_tag 'Search', :name => nil %>
        </div>
      <% end %>
    </div>
    <div class="product_list">
      <% @product.each do |product| %>
        <% unless product.user_id == current_user.id %>
          <%= link_to product_path(product.id) do %>
            <div class="product_content">
              <div class="product_image_">
                <% if product.product_image? %>
                  <img src="<%= product.product_image %>" class="icon_image user_show_icon" alt="商品画像">
                <% else %>
                  <img src="/assets/not_image.png" class="icon_image user_show_icon" alt="not_image" %>
                <% end %>
              </div>
              <div class="product_content_right">
                <div class="product_appeal_index">
                  <%= product.appeal %>
                </div>
                <div class="product_name_index">
                  <%= product.product_name%>
                </div>
                <div class="product_star">
                <div id="star-rate-<%= product.id %>"></div>
                  <script>
                    $('#star-rate-<%= product.id %>').empty();
                      $('#star-rate-<%= product.id %>').raty({
                        size: 36,
                        starOff:  '<%= asset_path('star-off.png') %>',
                        starOn : '<%= asset_path('star-on.png') %>',
                        starHalf: '<%= asset_path('star-half.png') %>',
                        half: true,
                        readOnly: true,
                        score: <%= product.evaluation %>,
                      });
                  </script>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="outer_border">
  <div class="content_products_show">
    <div class="product_name_area">
      <h2 class="product_appeal">
        <%= @product.appeal%>
      </h2>
      <div class="contributor">
        <p>投稿者名:</p>
        <%= link_to user_path(@product.user_id) do%>
          <%= @user.username %>
        <% end %>
      </div>
    </div>
    <div class="product_infomation">
      <div class="product_left">
        <div class="product_name">
          <%= @product.product_name%>
        </div>
        <div class="product_image">
          <% if @product.product_image? %>
            <img src="<%= @product.product_image %>" class="icon_image product_show_icon" alt="商品の画像">
          <% else %>
            <img src="/assets/not_image.png" class="icon_image product_show_icon" alt="商品の画像" %>
          <% end %>
        </div>
      </div>
      <div class="function">
        <div class="function_top">
          <div class="product_price">
            <p>価格</p>
            <%= @product.product_price%>円
          </div>
          <div class="product_alcohol">
            <p>度数</p>
            <%= @product.product_alcohol%>%
          </div>
          <div class="product_company">
            <p>販売会社</p>
            <%= @product.product_company%>
          </div>
        </div>
        <div class="function_bottom_product_show">
          <div class="product_introduction">
            <%= @product.product_introduction%>
          </div>
          <div class="product_star">
            <div id="star-rate-<%= @product.id %>"></div>
            <script>
              $('#star-rate-<%= @product.id %>').empty();
                $('#star-rate-<%= @product.id %>').raty({
                  size: 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= @product.evaluation %>,
                });
            </script>
          </div>
        </div>
      </div>
      <div class="like_area">
        <% if current_user.already_liked?(@product) %>
          <%= button_to product_like_path(@product), method: :delete, class: "likes" do %>
            <i class="fas fa-heart like-btn", id="liking-btn"></i>
          <% end %>
        <% else %>
          <%= button_to product_likes_path(@product), method: :product, class: "unlikes" do %>
            <i class="far fa-heart unlike-btn", id="nolike-btn"></i>
          <% end%>
        <% end %>
        <p class="like_count"><%= @product.likes.count %></p>
      </div>
    </div>
  </div>  
  <% if @user == current_user %>
    <p><%= link_to "編集する", edit_product_path %></p>
    <p><%= link_to "削除する", product_path(@product.id), method: :delete, data: { confirm: '削除しますか？' }%></p>
  <% end %>
</div>